name: saverecipe
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  image_picker: ^0.8.5
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  palette_generator: ^0.3.3
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.1.0
  flutter_image_compress: ^1.1.0
  # device_preview: ^0.4.5
  # cupertino_icons: ^0.1.3
  # provider: ^4.1.2
  # image_picker: ^0.6.6+5
  # shimmer: ^1.1.1
  # transparent_image: ^1.0.0
  # hive: ^1.4.3
  # hive_flutter: ^0.3.0+2
  # uuid: ^2.2.0
  # palette_generator: ^0.2.3
  # loading_overlay: ^0.2.1
  # flutter_spinkit: "^4.1.2"
  # flutter_image_compress: ^0.7.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  hive_generator: ^1.1.2
  
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
